# Generated by Django 4.0.10 on 2023-12-12 22:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=80)),
                ('desarrolladora', models.CharField(max_length=50)),
                ('plataformas', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descripcion', models.CharField(max_length=500)),
                ('portada', models.ImageField(blank=True, upload_to='portadas/')),
            ],
            options={
                'permissions': [('special_status', 'Puede ver los juegos')],
            },
        ),
        migrations.AddIndex(
            model_name='videojuego',
            index=models.Index(fields=['uuid'], name='id_index'),
        ),
    ]
